### ISSUE TITLE
[Feature Request] Make the root slash easier to click on

### ISSUE THREAD

**Issue by j-maffe** [pjeby/quick-explorer#68]
I really like using the inline title to navigate back to the upper folder or sibling files, but for me, the most important selection is the hardest. To select the root I'd have to aim at the measly forward slash at the start of the path. It'd be great if there was a name before it (maybe the vault's name) or just a bigger area to its left to make clicking on it smoother. Awesome work on the plugin!

**Comment by pjeby** [comment]
Have you tried using the "Quick Explorer: Browse Vault" command?  You can set a hotkey for it, or use another plugin (such as Commander) to add a header button for it.

**Comment by j-maffe** [comment]
Oh that's a great idea! I used the DoubleShift plugin to assign it to double alt and now it's so easy to navigate the entire tree. I knew Quick Explorer had good keyboard support but I didn't know it was even faster than the mouse. Nice!

**Comment by pjeby** [comment]
It's a bug - fixed in 0.2.8.  The "no file is open" view is not a standard FileView, that's what was throwing it off.  I didn't see the issue in 0.15.9 because on 0.15.9 there's no path in the view header, so there was no problem there.

**Comment by j-maffe** [comment]
Sorry for replying so late, but I think this bug is still there. Running the "Browse vault" command on a new tab doesn't do anything. That sort of makes sense because there is no address in the title bar on a new tab page.

**Comment by pjeby** [comment]
It works fine for me on Obsidian 1.1.10, even with Hidden Frame or Native Frame mode, no tab headers, and Style Settings configured to hide Quick Explorer entirely.  It just cascades from the upper left of the display, as it's supposed to.

**Comment by j-maffe** [comment]
Ok I created a brand new vault to make sure. Here's what I did:
- Installed Quick Explorer
- Installed Styler and enabled Hide Quick Explorer
- opened a new tab and tried the Browse vault command.
I guess you have it disabled?

**Comment by pjeby** [comment]
I enabled it for the test (using the Style Settings plugin, not familiar with "Styler".  You didn't mention what Obsidian version you're using, either.

**Comment by j-maffe** [comment]
Yes, sorry, Style Settings plugin. Running version 1.1.9.
I looked at the console log and it seems like there's an error when running the Browse Vault command:
```
Uncaught TypeError: Cannot read properties of null (reading 'containerEl')
    at A.visibleCrumb (plugin:quick-explorer:1:33483)
    at A.folderMenu (plugin:quick-explorer:1:33710)
    at A.browseVault (plugin:quick-explorer:1:33776)
    at Object.callback (plugin:quick-explorer:1:36563)
    at XN (app.js:1:1502974)
    at t.onChooseItem (app.js:1:1836164)
    at t.onChooseSuggestion (app.js:1:1726362)
    at t.selectSuggestion (app.js:1:1725912)
    at e.useSelectedItem (app.js:1:1539277)
    at Object.func (app.js:1:1537992)
```



When clicking on the root slash in the inline title at the top:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'file')
    at fe (plugin:quick-explorer:1:35265)
    at register.I.capture (plugin:quick-explorer:1:32056)
    at HTMLBodyElement.s (enhance.js:1:10270)
fe	@	plugin:quick-explorer:1
register.I.capture	@	plugin:quick-explorer:1
s	@	enhance.js:1
```

**Comment by pjeby** [comment]
Do you have Quick Explorer 0.2.8?

**Comment by j-maffe** [comment]
No, it was 0.2.7. It just updated and finally works!
I'm so confused though, why would it wait an entire month to update? I press the check for updates button every day.
The newly created testvault also downloaded 0.2.7 just yesterday. But when I checked for updates today, both vaults updated.
Well, thanks for your help anyway! I'm still super confused why this happened haha
